<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-28T14:44:01 IST" name="Default suite" finished-at="2024-08-28T14:44:20 IST" duration-ms="19030">
    <groups>
    </groups>
    <test started-at="2024-08-28T14:44:01 IST" name="Default test" finished-at="2024-08-28T14:44:20 IST" duration-ms="19030">
      <class name="com.DemoQA.TestCase.TestCase">
        <test-method is-config="true" signature="dataGeneration()[pri:0, instance:com.DemoQA.TestCase.TestCase@491b9b8]" started-at="2024-08-28T14:44:01 IST" name="dataGeneration" finished-at="2024-08-28T14:44:01 IST" duration-ms="48" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataGeneration -->
        <test-method is-config="true" signature="startBrowser()[pri:0, instance:com.DemoQA.TestCase.TestCase@491b9b8]" started-at="2024-08-28T14:44:01 IST" name="startBrowser" finished-at="2024-08-28T14:44:06 IST" duration-ms="5125" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method signature="TC02_LoginLogOut()[pri:2, instance:com.DemoQA.TestCase.TestCase@491b9b8]" started-at="2024-08-28T14:44:06 IST" name="TC02_LoginLogOut" description="Test to verify the login and logout functionality of the application" finished-at="2024-08-28T14:44:09 IST" duration-ms="3162" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_LoginLogOut -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.DemoQA.TestCase.TestCase@491b9b8]" started-at="2024-08-28T14:44:09 IST" name="closeBrowser" finished-at="2024-08-28T14:44:12 IST" duration-ms="2374" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="startBrowser()[pri:0, instance:com.DemoQA.TestCase.TestCase@491b9b8]" started-at="2024-08-28T14:44:12 IST" name="startBrowser" finished-at="2024-08-28T14:44:15 IST" duration-ms="3873" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method signature="TC17_FailedTestCase()[pri:17, instance:com.DemoQA.TestCase.TestCase@491b9b8]" started-at="2024-08-28T14:44:15 IST" name="TC17_FailedTestCase" description="Test to verify that user should NOT be able to login with invalid credentials_TestShouldFail" finished-at="2024-08-28T14:44:17 IST" duration-ms="1858" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.DemoQA.PageLayer.TC17_FailedTestCase.loginExpectedToFail(TC17_FailedTestCase.java:59)
at com.DemoQA.TestCase.TestCase.TC17_FailedTestCase(TestCase.java:150)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC17_FailedTestCase -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.DemoQA.TestCase.TestCase@491b9b8]" started-at="2024-08-28T14:44:17 IST" name="closeBrowser" finished-at="2024-08-28T14:44:20 IST" duration-ms="2243" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.DemoQA.TestCase.TestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
